# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=100)),
                ('link_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenshotFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[(b'aplite', b'Aplite'), (b'basalt', b'Basalt'), (b'chalk', b'Chalk')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScreenshotSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(b'^[/a-zA-Z0-9_-]+$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('folded_lines', models.TextField(default=b'[]')),
                ('file_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(b'^[/a-zA-Z0-9_-]+$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_files', to='ide.Project')),
            ],
            options={
                'ordering': ['file_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(null=True)),
                ('original_name', models.CharField(max_length=100)),
                ('code', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['original_name', '-session__date_added'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('kind', models.CharField(choices=[(b'batch', 'Batch Test'), (b'live', 'Live Test')], max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='ide.Project')),
            ],
            options={
                'ordering': ['-date_added'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ide.TestSession'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ide.TestFile'),
        ),
        migrations.AddField(
            model_name='testlog',
            name='test_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logfile', to='ide.TestRun'),
        ),
        migrations.AddField(
            model_name='screenshotset',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_sets', to='ide.TestFile'),
        ),
        migrations.AddField(
            model_name='screenshotfile',
            name='screenshot_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ide.ScreenshotSet'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='test_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='ide.TestLog'),
        ),
        migrations.AlterUniqueTogether(
            name='testrun',
            unique_together=set([('test', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='testfile',
            unique_together=set([('project', 'file_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='screenshotset',
            unique_together=set([('test', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='screenshotfile',
            unique_together=set([('platform', 'screenshot_set')]),
        ),
    ]
